from Book import BookItem
from EventDiscount import EventDiscount
from Rating import Rating

book3 = BookItem(78254,
                 "cover78254.png",
                 "Leave now, Human. You don't know what you are facing",
                 "Eoin Colfer",
                 "Artemis Fowl",
                 "296 page Hardcover",
                 9749000862,
                 "Tree Publishing",
                 "One day...",
                 "Great Story",
                 [],
                 "He found something",
                 ["Fantasy", "SCI-FI"],
                 "14-Dec-01",
                 Rating(),
                 EventDiscount())
book4 = BookItem(58488,
                 "cover58488.png",
                 "Welcome to the mysterious world of god.",
                 "Cosmos",
                 "Myth of God and Inhuman",
                 "147 page Hardcover",
                 9748241734,
                 "Phailin Publishing",
                 "One day....",
                 "Interesting Book",
                 [],
                 "The god have been angered",
                 ["Fantasy", "Historical"],
                 "17-Nov-01",
                 Rating(),
                 EventDiscount())
